package utils

func GetEnvVar_GESINV_URL_HTTP_API_AUTHENTICATIONSERVICE() string {
	return "GESINV_URL_HTTP_API_AUTHENTICATIONSERVICE"
}

func GetEnvVar_GESINV_URL_HTTP_API_EMAILSERVICE() string {
	return "GESINV_URL_HTTP_API_EMAILSERVICE"
}

func GetEnvVar_GESINV_URL_HTTP_API_PRODUCTSSERVICE() string {
	return "GESINV_URL_HTTP_API_PRODUCTSSERVICE"
}

func GetEnvVar_GESINV_URL_HTTP_API_SUBSCRIPTIONSSERVICE() string {
	return "GESINV_URL_HTTP_API_SUBSCRIPTIONSSERVICE"
}

func GetEnvVar_GESINV_JWT_SECRET() string {
	return "GESINV_JWT_SECRET"
}
